### ISSUE TITLE
Create Visualize validation profile

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-link#114]
- [x] #108

**Comment by tpluscode** [comment]
@bprusinowski @sosiology

Could we have IXT's feedback on what is required by Visualize?

**Comment by bprusinowski** [comment]
Hi @tpluscode, the first set of requirements comes from `rdf-cube-view-query` library (e.g. things like [this](https://github.com/zazuko/rdf-cube-view-query/blob/9acb62a2bd5e50a4febf8f871f3e52935c151a62/lib/View.js#L205-L208)).

For the things we keep directly inside our repo, I tried to summarize them below. Btw. the `dcterms:creator` is not a hard requirement for Visualize, we just don't show the creator tag if it's missing. But of course if would be good to enforce this on the data side 👍 

### Cube
_Required properties are listed below; if one's missing the application will throw an error._
- localized `schema:name`
- `schema.creativeWorkStatus`: `ns.adminVocabulary("CreativeWorkStatus/Published")` for published cube, otherwise cube is treated as a draft

### Dimensions

- Each dimension should have only one `dataType`
- `dataType` can't be equal to `ns.rdf.langString`
- For `TemporalDimensions` (`dim.out(ns.cube("meta/dataKind")).out(ns.rdf.type).term` === `ns.time.GeneralDateTimeDescription`) we need to have timeFormat: `dimension.datatype` is in
 
```ts
const timeFormats = new Map<string, string>([
  [ns.xsd.gYear.value, "%Y"],
  [ns.xsd.gYearMonth.value, "%Y-%m"],
  [ns.xsd.date.value, "%Y-%m-%d"],
  [ns.xsd.dateTime.value, "%Y-%m-%dT%H:%M:%S"],
]);
```

or timeUnit (`dim.out(ns.cube("meta/dataKind")).out(ns.time.unitType).term`) defined.

I think these are all the "hard requirements" related to data fetching that would make the application crash (except of _Each dimension should have only one `dataType`_ - here we just take the first one, which might lead to some problems down the road).

I didn't include recommendations on what "should" be included in a cube to make Visualize happy. Should I also list these properties that can be missing, but are displayed somewhere if present (e.g. creators, contact points, landing page, etc)?

cc @adintegra @sosiology

**Comment by Rdataflow** [comment]
@bprusinowski can add some words on how you treat timezones? i.e. 
- `2024-01-18T15:24:07Z`
- `2024-01-18T14:24:07+01:00`

**Comment by Rdataflow** [comment]
@bprusinowski can you explain more about the implicit requirements of visualize: i.e. 
- nodeKind is required and shall be in ( `IRI` | `Literal` )
- scaleType is required to be set
- ... and what more

and it would be interesting to also share recommendations _(those could lead to messages of `severety Warning`)_: i.e.
- if list length is less than 5000 values should be made available in `<dimX> sh:in (...)`
- ... and what more

**Comment by Rdataflow** [comment]
@bprusinowski how many dcat:landigPage can a cube have max?

cc @dbaeder

**Comment by bprusinowski** [comment]
@Rdataflow thanks for raising this point – we currently require either zero or one, non-localized string or more than one, localized strings (so we can filter them down to one entry per language) – see https://github.com/visualize-admin/visualization-tool/blob/2aa07b96db9a057281bef3cad2b7d08c49c5e1a7/app/rdf/query-cube-metadata.ts#L143-L146

**Comment by kronmar** [comment]
Found an interesting edge-case: [https://s.zazuko.com/xmbYnD]()

We have here a cube, with a dimension with 13 distinct hierarchies parallel to each other. Using `cat cube-constraint.ttl | npx barnard59 cube check-metadata --profile https://cube.link/latest/shape/standalone-constraint-constraint` returns no errors.

Nevertheless, Visualize can't handle this case:
![image](https://github.com/zazuko/cube-link/assets/95312586/5c5905a3-6f13-4cae-b6ca-3ced6fe89832)

The visualization issue can be fixed rather easily by giving each hierarchy a distinct name. Would it be possible to catch this issue in the `standalone-constraint-constraint.ttl`?

cc @Rdataflow @tpluscode

**Comment by tpluscode** [comment]
@bprusinowski I started the profile for visualize in #141 

I applied the rules for `sh:datatype` and temporal dimensions. The other point may be added as more warnings but we'd need better support for that first.

**Comment by tpluscode** [comment]
About, `time:unitType`. The spec allows `time:unitYear`, `time:unitMonth`, `time:unitWeek`, `time:unitDay`, `time:unitHour`, `time:unitMinute` and `time:unitSecond`. Are all those supported?

**Comment by bprusinowski** [comment]
@tpluscode cool! Yes, all of them are supported, see https://github.com/visualize-admin/visualization-tool/blob/2b77e5226adbdca7c43d592d57614a4791e696e7/app/rdf/parse.ts#L98-L106
