### ISSUE TITLE
CI jobs on Windows are failing

### ISSUE THREAD

**Issue by ludovicm67** [zazuko/cube-link#173]
By looking at the CI jobs, it seems that all jobs that are run on Windows are always failing for now during the installation of the dependencies step, like here: https://github.com/zazuko/cube-link/actions/runs/8702440720/job/23866486071.

**Comment by ludovicm67** [comment]
I was able to find the cause: https://github.com/approvals/Approvals.NodeJS/issues/176

We need to wait for a fix.

**Comment by tpluscode** [comment]
Might also pin to a past version?

**Comment by ludovicm67** [comment]
The pin should only be a temporary solution the time a fix is provided.
So once the fix is available, we should roll back the custom change.

**Comment by maxwelliverson** [comment]
This is specifically caused by the a recent security patch to node, whereby `spawn`  now rejects batch files. Instead, the script should be spawned in a new shell, and this can be done simply by using `{ shell: true }`, as indicated by https://github.com/nodejs/node/issues/52554#issuecomment-2060026269

This seemed to be the expected fix going forward; given that the issue was caused by patching a security vulnerability, it won't be reverted.
